data_root: ./rag_store
embeddings:
  model: BAAI/bge-base-en-v1.5
  batch_size: 64
  device: auto
faiss:
  gutenberg: &id001
    path: ./rag_store/embeddings/gutenberg
    factory: IVF2048,PQ64
    dim: 768
  reading:
    path: ./rag_store/embeddings/reading
    factory: Flat
    dim: 768
  books: *id001
retrieval:
  top_k: 24
  per_shard:
    gutenberg: 16
    reading: 16
reranker:
  enabled: true
  model: BAAI/bge-reranker-base
  top_n: 8
ocr:
  enabled: true
llama_cpp:
  model_path: D:\PythonProject\LLM_Multi_Agent\models\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf
  n_ctx: 4096
  n_batch: 512
  n_gpu_layers: 30
  temperature: 0.2
  top_p: 0.9
  verbose: false
citations:
  paragraphs: true
